# Generated by Django 2.2.7 on 2019-12-12 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'мужчина'), ('FEMALE', 'женщина')], max_length=10)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'женат/замужем'), ('UNMARRIED', 'холост/не замужем')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('upper_border', models.IntegerField()),
                ('lower_border', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Department')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Post')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Post')),
            ],
        ),
    ]
